### ISSUE TITLE
  Starnekit: Теперь заклеив рот скотчем, заткнуться не заставишь

### ISSUE THREAD

**Issue by LunarDarkness** [animusdev/AuroraBlue#4]
Вернуть "Mmmph!" вместо слов при скотче на рте, люди говорят сквозь скотч.

**Comment by Doloreere** [comment]
О, минутку.

**Comment by Doloreere** [comment]
https://github.com/animusdev/AuroraBlue/commit/d7d50285992fff8a455e28e092212e8b0ac2ecd1
