### ISSUE TITLE
Телепорт вампиров

### ISSUE THREAD

**Issue by ZerlGray** [animusdev/AuroraBlue#42]
Vail Stap или как то так называется абилка вампиров - она позволяет телепортироваться на тайлы в зоне видимости. Работает именно как телепорт, а не как абилка магов, которая позволяет проходить сквозь объекты. Так вот. Она не работает. Все тайлы считаются недоступными для телепортации.

**Comment by MorJams** [comment]
Но ведь работает, в темноте же нужно быть.

**Comment by ZerlGray** [comment]
В темноте? Хм, значит я что то не верно читал. Тогда ок. Соррян на фейлоиссуи.

А телепорт вернули в рабочее состояние?

И да, у вас теперь личей можно сломать лазерганами. Это нормально? (В плане - при убийстве лича-мага раунд кончается, несмотря на возможность юзануть темное воскрешение).
